from tkinter import *
from tkinter import ttk as ttk
import pyglet

root = Tk()
root.resizable(False,False)
root.config(bg="#202020")

style = ttk.Style()
style.theme_use('clam')
style.configure('my.TButton', background = "#202020", relief=FLAT, padding=0)
style.configure('my.TLabel', padding=20)

pyglet.font.add_file("font/HYWenHei.ttf")

# IMAGES
albedo = PhotoImage(file="img/Characters/Albedo.png")
amber = PhotoImage(file="img/Characters/Amber.png")
barbara = PhotoImage(file="img/Characters/Barbara.png")
beidou = PhotoImage(file="img/Characters/Beidou.png")
bennett = PhotoImage(file="img/Characters/Bennett.png")
chongyun = PhotoImage(file="img/Characters/Chongyun.png")
diluc = PhotoImage(file="img/Characters/Diluc.png")
diona = PhotoImage(file="img/Characters/Diona.png")
fischl = PhotoImage(file="img/Characters/Fischl.png")
jean = PhotoImage(file="img/Characters/Jean.png")
kaeya = PhotoImage(file="img/Characters/Kaeya.png")
qeqing = PhotoImage(file="img/Characters/Keqing.png")
klee = PhotoImage(file="img/Characters/Klee.png")
lisa = PhotoImage(file="img/Characters/Lisa.png")
mona = PhotoImage(file="img/Characters/Mona.png")
ningguang = PhotoImage(file="img/Characters/Ningguang.png")
noelle = PhotoImage(file="img/Characters/Noelle.png")
qiqi = PhotoImage(file="img/Characters/Qiqi.png")
razor = PhotoImage(file="img/Characters/Razor.png")
sucrose = PhotoImage(file="img/Characters/Sucrose.png")
tartaglia = PhotoImage(file="img/Characters/Tartaglia.png")
traveler_Anemo = PhotoImage(file="img/Characters/Traveler (Anemo).png")
traveler_Geo = PhotoImage(file="img/Characters/Traveler (Geo).png")
venti = PhotoImage(file="img/Characters/Venti.png")
xiangling = PhotoImage(file="img/Characters/Xiangling.png")
xiao = PhotoImage(file="img/Characters/Xiao.png")
xingqiu = PhotoImage(file="img/Characters/Xingqiu.png")
xinyan = PhotoImage(file="img/Characters/Xinyan.png")
zhongli = PhotoImage(file="img/Characters/Zhongli.png")

letreiro = ttk.Label(root, text="Characters", font=("HYWenHei-85W", 25), foreground="White", background="#202020", style='my.TLabel')
letreiro.grid(row=0, columnspan=10)

bt_albedo = ttk.Button(root, image=albedo, style="my.TButton")
bt_albedo.grid(row=1, column=0)
bt_amber = ttk.Button(root, image=amber, style="my.TButton")
bt_amber.grid(row=1, column=1)
bt_barbara = ttk.Button(root, image=barbara, style="my.TButton")
bt_barbara.grid(row=1, column=2)
bt_beidou = ttk.Button(root, image=beidou, style="my.TButton")
bt_beidou.grid(row=1, column=3)
bt_bennett = ttk.Button(root, image=bennett, style="my.TButton")
bt_bennett.grid(row=1, column=4)
bt_chongyun = ttk.Button(root, image=chongyun, style="my.TButton")
bt_chongyun.grid(row=1, column=5)
bt_diluc = ttk.Button(root, image=diluc, style="my.TButton")
bt_diluc.grid(row=1, column=6)
bt_diona = ttk.Button(root, image=diona, style="my.TButton")
bt_diona.grid(row=1, column=7)
bt_fischl = ttk.Button(root, image=fischl, style="my.TButton")
bt_fischl.grid(row=1, column=8)
bt_jean = ttk.Button(root, image=jean, style="my.TButton")
bt_jean.grid(row=1, column=9)
bt_albedo = ttk.Button(root, image=albedo, style="my.TButton")
bt_albedo.grid(row=1, column=0)
bt_amber = ttk.Button(root, image=amber, style="my.TButton")
bt_amber.grid(row=1, column=1)
bt_barbara = ttk.Button(root, image=barbara, style="my.TButton")
bt_barbara.grid(row=1, column=2)
bt_beidou = ttk.Button(root, image=beidou, style="my.TButton")
bt_beidou.grid(row=1, column=3)
bt_bennett = ttk.Button(root, image=bennett, style="my.TButton")
bt_bennett.grid(row=1, column=4)
bt_chongyun = ttk.Button(root, image=chongyun, style="my.TButton")
bt_chongyun.grid(row=1, column=5)
bt_diluc = ttk.Button(root, image=diluc, style="my.TButton")
bt_diluc.grid(row=1, column=6)
bt_diona = ttk.Button(root, image=diona, style="my.TButton")
bt_diona.grid(row=1, column=7)
bt_fischl = ttk.Button(root, image=fischl, style="my.TButton")
bt_fischl.grid(row=1, column=8)
bt_jean = ttk.Button(root, image=jean, style="my.TButton")
bt_jean.grid(row=1, column=9)
bt_albedo = ttk.Button(root, image=albedo, style="my.TButton")
bt_albedo.grid(row=1, column=0)
bt_amber = ttk.Button(root, image=amber, style="my.TButton")
bt_amber.grid(row=1, column=1)
bt_barbara = ttk.Button(root, image=barbara, style="my.TButton")
bt_barbara.grid(row=1, column=2)
bt_beidou = ttk.Button(root, image=beidou, style="my.TButton")
bt_beidou.grid(row=1, column=3)
bt_bennett = ttk.Button(root, image=bennett, style="my.TButton")
bt_bennett.grid(row=1, column=4)
bt_chongyun = ttk.Button(root, image=chongyun, style="my.TButton")
bt_chongyun.grid(row=1, column=5)
bt_diluc = ttk.Button(root, image=diluc, style="my.TButton")
bt_diluc.grid(row=1, column=6)
bt_diona = ttk.Button(root, image=diona, style="my.TButton")
bt_diona.grid(row=1, column=7)
bt_fischl = ttk.Button(root, image=fischl, style="my.TButton")
bt_fischl.grid(row=1, column=8)
bt_jean = ttk.Button(root, image=jean, style="my.TButton")
bt_jean.grid(row=1, column=9)
bt_albedo = ttk.Button(root, image=albedo, style="my.TButton")
bt_albedo.grid(row=1, column=0)
bt_amber = ttk.Button(root, image=amber, style="my.TButton")
bt_amber.grid(row=1, column=1)
bt_barbara = ttk.Button(root, image=barbara, style="my.TButton")
bt_barbara.grid(row=1, column=2)
bt_beidou = ttk.Button(root, image=beidou, style="my.TButton")
bt_beidou.grid(row=1, column=3)
bt_bennett = ttk.Button(root, image=bennett, style="my.TButton")
bt_bennett.grid(row=1, column=4)
bt_chongyun = ttk.Button(root, image=chongyun, style="my.TButton")
bt_chongyun.grid(row=1, column=5)
bt_diluc = ttk.Button(root, image=diluc, style="my.TButton")
bt_diluc.grid(row=1, column=6)
bt_diona = ttk.Button(root, image=diona, style="my.TButton")
bt_diona.grid(row=1, column=7)
bt_fischl = ttk.Button(root, image=fischl, style="my.TButton")
bt_fischl.grid(row=1, column=8)
bt_jean = ttk.Button(root, image=jean, style="my.TButton")
bt_jean.grid(row=1, column=9)
bt_albedo = ttk.Button(root, image=albedo, style="my.TButton")
bt_albedo.grid(row=1, column=0)
bt_amber = ttk.Button(root, image=amber, style="my.TButton")
bt_amber.grid(row=1, column=1)
bt_barbara = ttk.Button(root, image=barbara, style="my.TButton")
bt_barbara.grid(row=1, column=2)
bt_beidou = ttk.Button(root, image=beidou, style="my.TButton")
bt_beidou.grid(row=1, column=3)
bt_bennett = ttk.Button(root, image=bennett, style="my.TButton")
bt_bennett.grid(row=1, column=4)
bt_chongyun = ttk.Button(root, image=chongyun, style="my.TButton")
bt_chongyun.grid(row=1, column=5)
bt_diluc = ttk.Button(root, image=diluc, style="my.TButton")
bt_diluc.grid(row=1, column=6)
bt_diona = ttk.Button(root, image=diona, style="my.TButton")
bt_diona.grid(row=1, column=7)
bt_fischl = ttk.Button(root, image=fischl, style="my.TButton")
bt_fischl.grid(row=1, column=8)
bt_jean = ttk.Button(root, image=jean, style="my.TButton")
bt_jean.grid(row=1, column=9)
bt_albedo = ttk.Button(root, image=albedo, style="my.TButton")
bt_albedo.grid(row=1, column=0)
bt_amber = ttk.Button(root, image=amber, style="my.TButton")
bt_amber.grid(row=1, column=1)
bt_barbara = ttk.Button(root, image=barbara, style="my.TButton")
bt_barbara.grid(row=1, column=2)
bt_beidou = ttk.Button(root, image=beidou, style="my.TButton")
bt_beidou.grid(row=1, column=3)
bt_bennett = ttk.Button(root, image=bennett, style="my.TButton")
bt_bennett.grid(row=1, column=4)
bt_chongyun = ttk.Button(root, image=chongyun, style="my.TButton")
bt_chongyun.grid(row=1, column=5)
bt_diluc = ttk.Button(root, image=diluc, style="my.TButton")
bt_diluc.grid(row=1, column=6)
bt_diona = ttk.Button(root, image=diona, style="my.TButton")
bt_diona.grid(row=1, column=7)
bt_fischl = ttk.Button(root, image=fischl, style="my.TButton")
bt_fischl.grid(row=1, column=8)
bt_jean = ttk.Button(root, image=jean, style="my.TButton")
bt_jean.grid(row=1, column=9)
bt_albedo = ttk.Button(root, image=albedo, style="my.TButton")
bt_albedo.grid(row=1, column=0)
bt_amber = ttk.Button(root, image=amber, style="my.TButton")
bt_amber.grid(row=1, column=1)
bt_barbara = ttk.Button(root, image=barbara, style="my.TButton")
bt_barbara.grid(row=1, column=2)
bt_beidou = ttk.Button(root, image=beidou, style="my.TButton")
bt_beidou.grid(row=1, column=3)
bt_bennett = ttk.Button(root, image=bennett, style="my.TButton")
bt_bennett.grid(row=1, column=4)
bt_chongyun = ttk.Button(root, image=chongyun, style="my.TButton")
bt_chongyun.grid(row=1, column=5)
bt_diluc = ttk.Button(root, image=diluc, style="my.TButton")
bt_diluc.grid(row=1, column=6)
bt_diona = ttk.Button(root, image=diona, style="my.TButton")
bt_diona.grid(row=1, column=7)
bt_fischl = ttk.Button(root, image=fischl, style="my.TButton")
bt_fischl.grid(row=1, column=8)
bt_jean = ttk.Button(root, image=jean, style="my.TButton")
bt_jean.grid(row=1, column=9)
bt_albedo = ttk.Button(root, image=albedo, style="my.TButton")
bt_albedo.grid(row=1, column=0)
bt_amber = ttk.Button(root, image=amber, style="my.TButton")
bt_amber.grid(row=1, column=1)
bt_barbara = ttk.Button(root, image=barbara, style="my.TButton")
bt_barbara.grid(row=1, column=2)
bt_beidou = ttk.Button(root, image=beidou, style="my.TButton")
bt_beidou.grid(row=1, column=3)
bt_bennett = ttk.Button(root, image=bennett, style="my.TButton")
bt_bennett.grid(row=1, column=4)
bt_chongyun = ttk.Button(root, image=chongyun, style="my.TButton")
bt_chongyun.grid(row=1, column=5)
bt_diluc = ttk.Button(root, image=diluc, style="my.TButton")
bt_diluc.grid(row=1, column=6)
bt_diona = ttk.Button(root, image=diona, style="my.TButton")
bt_diona.grid(row=1, column=7)
bt_fischl = ttk.Button(root, image=fischl, style="my.TButton")
bt_fischl.grid(row=1, column=8)
bt_jean = ttk.Button(root, image=jean, style="my.TButton")
bt_jean.grid(row=1, column=9)
bt_albedo = ttk.Button(root, image=albedo, style="my.TButton")
bt_albedo.grid(row=1, column=0)
bt_amber = ttk.Button(root, image=amber, style="my.TButton")
bt_amber.grid(row=1, column=1)
bt_barbara = ttk.Button(root, image=barbara, style="my.TButton")
bt_barbara.grid(row=1, column=2)
bt_beidou = ttk.Button(root, image=beidou, style="my.TButton")
bt_beidou.grid(row=1, column=3)
bt_bennett = ttk.Button(root, image=bennett, style="my.TButton")
bt_bennett.grid(row=1, column=4)
bt_chongyun = ttk.Button(root, image=chongyun, style="my.TButton")
bt_chongyun.grid(row=1, column=5)
bt_diluc = ttk.Button(root, image=diluc, style="my.TButton")
bt_diluc.grid(row=1, column=6)
bt_diona = ttk.Button(root, image=diona, style="my.TButton")
bt_diona.grid(row=1, column=7)
bt_fischl = ttk.Button(root, image=fischl, style="my.TButton")
bt_fischl.grid(row=1, column=8)
bt_jean = ttk.Button(root, image=jean, style="my.TButton")
bt_jean.grid(row=1, column=9)
bt_albedo = ttk.Button(root, image=albedo, style="my.TButton")
bt_albedo.grid(row=1, column=0)
bt_amber = ttk.Button(root, image=amber, style="my.TButton")
bt_amber.grid(row=1, column=1)
bt_barbara = ttk.Button(root, image=barbara, style="my.TButton")
bt_barbara.grid(row=1, column=2)
bt_beidou = ttk.Button(root, image=beidou, style="my.TButton")
bt_beidou.grid(row=1, column=3)
bt_bennett = ttk.Button(root, image=bennett, style="my.TButton")
bt_bennett.grid(row=1, column=4)
bt_chongyun = ttk.Button(root, image=chongyun, style="my.TButton")
bt_chongyun.grid(row=1, column=5)
bt_diluc = ttk.Button(root, image=diluc, style="my.TButton")
bt_diluc.grid(row=1, column=6)
bt_diona = ttk.Button(root, image=diona, style="my.TButton")
bt_diona.grid(row=1, column=7)
bt_fischl = ttk.Button(root, image=fischl, style="my.TButton")
bt_fischl.grid(row=1, column=8)
bt_jean = ttk.Button(root, image=jean, style="my.TButton")
bt_jean.grid(row=1, column=9)
bt_albedo = ttk.Button(root, image=albedo, style="my.TButton")
bt_albedo.grid(row=1, column=0)
bt_amber = ttk.Button(root, image=amber, style="my.TButton")
bt_amber.grid(row=1, column=1)
bt_barbara = ttk.Button(root, image=barbara, style="my.TButton")
bt_barbara.grid(row=1, column=2)
bt_beidou = ttk.Button(root, image=beidou, style="my.TButton")
bt_beidou.grid(row=1, column=3)
bt_bennett = ttk.Button(root, image=bennett, style="my.TButton")
bt_bennett.grid(row=1, column=4)
bt_chongyun = ttk.Button(root, image=chongyun, style="my.TButton")
bt_chongyun.grid(row=1, column=5)
bt_diluc = ttk.Button(root, image=diluc, style="my.TButton")
bt_diluc.grid(row=1, column=6)
bt_diona = ttk.Button(root, image=diona, style="my.TButton")
bt_diona.grid(row=1, column=7)
bt_fischl = ttk.Button(root, image=fischl, style="my.TButton")
bt_fischl.grid(row=1, column=8)
bt_jean = ttk.Button(root, image=jean, style="my.TButton")
bt_jean.grid(row=1, column=9)
bt_albedo = ttk.Button(root, image=albedo, style="my.TButton")
bt_albedo.grid(row=1, column=0)
bt_amber = ttk.Button(root, image=amber, style="my.TButton")
bt_amber.grid(row=1, column=1)
bt_barbara = ttk.Button(root, image=barbara, style="my.TButton")
bt_barbara.grid(row=1, column=2)
bt_beidou = ttk.Button(root, image=beidou, style="my.TButton")
bt_beidou.grid(row=1, column=3)
bt_bennett = ttk.Button(root, image=bennett, style="my.TButton")
bt_bennett.grid(row=1, column=4)
bt_chongyun = ttk.Button(root, image=chongyun, style="my.TButton")
bt_chongyun.grid(row=1, column=5)
bt_diluc = ttk.Button(root, image=diluc, style="my.TButton")
bt_diluc.grid(row=1, column=6)
bt_diona = ttk.Button(root, image=diona, style="my.TButton")
bt_diona.grid(row=1, column=7)
bt_fischl = ttk.Button(root, image=fischl, style="my.TButton")
bt_fischl.grid(row=1, column=8)
bt_jean = ttk.Button(root, image=jean, style="my.TButton")
bt_jean.grid(row=1, column=9)
bt_albedo = ttk.Button(root, image=albedo, style="my.TButton")
bt_albedo.grid(row=1, column=0)
bt_amber = ttk.Button(root, image=amber, style="my.TButton")
bt_amber.grid(row=1, column=1)
bt_barbara = ttk.Button(root, image=barbara, style="my.TButton")
bt_barbara.grid(row=1, column=2)
bt_beidou = ttk.Button(root, image=beidou, style="my.TButton")
bt_beidou.grid(row=1, column=3)
bt_bennett = ttk.Button(root, image=bennett, style="my.TButton")
bt_bennett.grid(row=1, column=4)
bt_chongyun = ttk.Button(root, image=chongyun, style="my.TButton")
bt_chongyun.grid(row=1, column=5)
bt_diluc = ttk.Button(root, image=diluc, style="my.TButton")
bt_diluc.grid(row=1, column=6)
bt_diona = ttk.Button(root, image=diona, style="my.TButton")
bt_diona.grid(row=1, column=7)
bt_fischl = ttk.Button(root, image=fischl, style="my.TButton")
bt_fischl.grid(row=1, column=8)
bt_jean = ttk.Button(root, image=jean, style="my.TButton")
bt_jean.grid(row=1, column=9)
bt_albedo = ttk.Button(root, image=albedo, style="my.TButton")
bt_albedo.grid(row=1, column=0)
bt_amber = ttk.Button(root, image=amber, style="my.TButton")
bt_amber.grid(row=1, column=1)
bt_barbara = ttk.Button(root, image=barbara, style="my.TButton")
bt_barbara.grid(row=1, column=2)
bt_beidou = ttk.Button(root, image=beidou, style="my.TButton")
bt_beidou.grid(row=1, column=3)
bt_bennett = ttk.Button(root, image=bennett, style="my.TButton")
bt_bennett.grid(row=1, column=4)
bt_chongyun = ttk.Button(root, image=chongyun, style="my.TButton")
bt_chongyun.grid(row=1, column=5)
bt_diluc = ttk.Button(root, image=diluc, style="my.TButton")
bt_diluc.grid(row=1, column=6)
bt_diona = ttk.Button(root, image=diona, style="my.TButton")
bt_diona.grid(row=1, column=7)
bt_fischl = ttk.Button(root, image=fischl, style="my.TButton")
bt_fischl.grid(row=1, column=8)
bt_jean = ttk.Button(root, image=jean, style="my.TButton")
bt_jean.grid(row=1, column=9)
bt_albedo = ttk.Button(root, image=albedo, style="my.TButton")
bt_albedo.grid(row=1, column=0)
bt_amber = ttk.Button(root, image=amber, style="my.TButton")
bt_amber.grid(row=1, column=1)
bt_barbara = ttk.Button(root, image=barbara, style="my.TButton")
bt_barbara.grid(row=1, column=2)
bt_beidou = ttk.Button(root, image=beidou, style="my.TButton")
bt_beidou.grid(row=1, column=3)
bt_bennett = ttk.Button(root, image=bennett, style="my.TButton")
bt_bennett.grid(row=1, column=4)
bt_chongyun = ttk.Button(root, image=chongyun, style="my.TButton")
bt_chongyun.grid(row=1, column=5)
bt_diluc = ttk.Button(root, image=diluc, style="my.TButton")
bt_diluc.grid(row=1, column=6)
bt_diona = ttk.Button(root, image=diona, style="my.TButton")
bt_diona.grid(row=1, column=7)
bt_fischl = ttk.Button(root, image=fischl, style="my.TButton")
bt_fischl.grid(row=1, column=8)
bt_jean = ttk.Button(root, image=jean, style="my.TButton")
bt_jean.grid(row=1, column=9)
bt_albedo = ttk.Button(root, image=albedo, style="my.TButton")
bt_albedo.grid(row=1, column=0)
bt_amber = ttk.Button(root, image=amber, style="my.TButton")
bt_amber.grid(row=1, column=1)
bt_barbara = ttk.Button(root, image=barbara, style="my.TButton")
bt_barbara.grid(row=1, column=2)
bt_beidou = ttk.Button(root, image=beidou, style="my.TButton")
bt_beidou.grid(row=1, column=3)
bt_bennett = ttk.Button(root, image=bennett, style="my.TButton")
bt_bennett.grid(row=1, column=4)
bt_chongyun = ttk.Button(root, image=chongyun, style="my.TButton")
bt_chongyun.grid(row=1, column=5)
bt_diluc = ttk.Button(root, image=diluc, style="my.TButton")
bt_diluc.grid(row=1, column=6)
bt_diona = ttk.Button(root, image=diona, style="my.TButton")
bt_diona.grid(row=1, column=7)
bt_fischl = ttk.Button(root, image=fischl, style="my.TButton")
bt_fischl.grid(row=1, column=8)
bt_jean = ttk.Button(root, image=jean, style="my.TButton")
bt_jean.grid(row=1, column=9)
bt_albedo = ttk.Button(root, image=albedo, style="my.TButton")
bt_albedo.grid(row=1, column=0)
bt_amber = ttk.Button(root, image=amber, style="my.TButton")
bt_amber.grid(row=1, column=1)
bt_barbara = ttk.Button(root, image=barbara, style="my.TButton")
bt_barbara.grid(row=1, column=2)
bt_beidou = ttk.Button(root, image=beidou, style="my.TButton")
bt_beidou.grid(row=1, column=3)
bt_bennett = ttk.Button(root, image=bennett, style="my.TButton")
bt_bennett.grid(row=1, column=4)
bt_chongyun = ttk.Button(root, image=chongyun, style="my.TButton")
bt_chongyun.grid(row=1, column=5)
bt_diluc = ttk.Button(root, image=diluc, style="my.TButton")
bt_diluc.grid(row=1, column=6)
bt_diona = ttk.Button(root, image=diona, style="my.TButton")
bt_diona.grid(row=1, column=7)
bt_fischl = ttk.Button(root, image=fischl, style="my.TButton")
bt_fischl.grid(row=1, column=8)
bt_jean = ttk.Button(root, image=jean, style="my.TButton")
bt_jean.grid(row=1, column=9)
bt_albedo = ttk.Button(root, image=albedo, style="my.TButton")
bt_albedo.grid(row=1, column=0)
bt_amber = ttk.Button(root, image=amber, style="my.TButton")
bt_amber.grid(row=1, column=1)
bt_barbara = ttk.Button(root, image=barbara, style="my.TButton")
bt_barbara.grid(row=1, column=2)
bt_beidou = ttk.Button(root, image=beidou, style="my.TButton")
bt_beidou.grid(row=1, column=3)
bt_bennett = ttk.Button(root, image=bennett, style="my.TButton")
bt_bennett.grid(row=1, column=4)
bt_chongyun = ttk.Button(root, image=chongyun, style="my.TButton")
bt_chongyun.grid(row=1, column=5)
bt_diluc = ttk.Button(root, image=diluc, style="my.TButton")
bt_diluc.grid(row=1, column=6)
bt_diona = ttk.Button(root, image=diona, style="my.TButton")
bt_diona.grid(row=1, column=7)
bt_fischl = ttk.Button(root, image=fischl, style="my.TButton")
bt_fischl.grid(row=1, column=8)
bt_jean = ttk.Button(root, image=jean, style="my.TButton")
bt_jean.grid(row=1, column=9)
bt_albedo = ttk.Button(root, image=albedo, style="my.TButton")
bt_albedo.grid(row=1, column=0)
bt_amber = ttk.Button(root, image=amber, style="my.TButton")
bt_amber.grid(row=1, column=1)
bt_barbara = ttk.Button(root, image=barbara, style="my.TButton")
bt_barbara.grid(row=1, column=2)
bt_beidou = ttk.Button(root, image=beidou, style="my.TButton")
bt_beidou.grid(row=1, column=3)
bt_bennett = ttk.Button(root, image=bennett, style="my.TButton")
bt_bennett.grid(row=1, column=4)
bt_chongyun = ttk.Button(root, image=chongyun, style="my.TButton")
bt_chongyun.grid(row=1, column=5)
bt_diluc = ttk.Button(root, image=diluc, style="my.TButton")
bt_diluc.grid(row=1, column=6)
bt_diona = ttk.Button(root, image=diona, style="my.TButton")
bt_diona.grid(row=1, column=7)
bt_fischl = ttk.Button(root, image=fischl, style="my.TButton")
bt_fischl.grid(row=1, column=8)
bt_jean = ttk.Button(root, image=jean, style="my.TButton")
bt_jean.grid(row=1, column=9)
bt_albedo = ttk.Button(root, image=albedo, style="my.TButton")
bt_albedo.grid(row=1, column=0)
bt_amber = ttk.Button(root, image=amber, style="my.TButton")
bt_amber.grid(row=1, column=1)
bt_barbara = ttk.Button(root, image=barbara, style="my.TButton")
bt_barbara.grid(row=1, column=2)
bt_beidou = ttk.Button(root, image=beidou, style="my.TButton")
bt_beidou.grid(row=1, column=3)
bt_bennett = ttk.Button(root, image=bennett, style="my.TButton")
bt_bennett.grid(row=1, column=4)
bt_chongyun = ttk.Button(root, image=chongyun, style="my.TButton")
bt_chongyun.grid(row=1, column=5)
bt_diluc = ttk.Button(root, image=diluc, style="my.TButton")
bt_diluc.grid(row=1, column=6)
bt_diona = ttk.Button(root, image=diona, style="my.TButton")
bt_diona.grid(row=1, column=7)
bt_fischl = ttk.Button(root, image=fischl, style="my.TButton")
bt_fischl.grid(row=1, column=8)
bt_jean = ttk.Button(root, image=jean, style="my.TButton")
bt_jean.grid(row=1, column=9)
bt_albedo = ttk.Button(root, image=albedo, style="my.TButton")
bt_albedo.grid(row=1, column=0)
bt_amber = ttk.Button(root, image=amber, style="my.TButton")
bt_amber.grid(row=1, column=1)
bt_barbara = ttk.Button(root, image=barbara, style="my.TButton")
bt_barbara.grid(row=1, column=2)
bt_beidou = ttk.Button(root, image=beidou, style="my.TButton")
bt_beidou.grid(row=1, column=3)
bt_bennett = ttk.Button(root, image=bennett, style="my.TButton")
bt_bennett.grid(row=1, column=4)
bt_chongyun = ttk.Button(root, image=chongyun, style="my.TButton")
bt_chongyun.grid(row=1, column=5)
bt_diluc = ttk.Button(root, image=diluc, style="my.TButton")
bt_diluc.grid(row=1, column=6)
bt_diona = ttk.Button(root, image=diona, style="my.TButton")
bt_diona.grid(row=1, column=7)
bt_fischl = ttk.Button(root, image=fischl, style="my.TButton")
bt_fischl.grid(row=1, column=8)
bt_jean = ttk.Button(root, image=jean, style="my.TButton")
bt_jean.grid(row=1, column=9)
bt_albedo = ttk.Button(root, image=albedo, style="my.TButton")
bt_albedo.grid(row=1, column=0)
bt_amber = ttk.Button(root, image=amber, style="my.TButton")
bt_amber.grid(row=1, column=1)
bt_barbara = ttk.Button(root, image=barbara, style="my.TButton")
bt_barbara.grid(row=1, column=2)
bt_beidou = ttk.Button(root, image=beidou, style="my.TButton")
bt_beidou.grid(row=1, column=3)
bt_bennett = ttk.Button(root, image=bennett, style="my.TButton")
bt_bennett.grid(row=1, column=4)
bt_chongyun = ttk.Button(root, image=chongyun, style="my.TButton")
bt_chongyun.grid(row=1, column=5)
bt_diluc = ttk.Button(root, image=diluc, style="my.TButton")
bt_diluc.grid(row=1, column=6)
bt_diona = ttk.Button(root, image=diona, style="my.TButton")
bt_diona.grid(row=1, column=7)
bt_fischl = ttk.Button(root, image=fischl, style="my.TButton")
bt_fischl.grid(row=1, column=8)
bt_jean = ttk.Button(root, image=jean, style="my.TButton")
bt_jean.grid(row=1, column=9)
bt_albedo = ttk.Button(root, image=albedo, style="my.TButton")
bt_albedo.grid(row=1, column=0)
bt_amber = ttk.Button(root, image=amber, style="my.TButton")
bt_amber.grid(row=1, column=1)
bt_barbara = ttk.Button(root, image=barbara, style="my.TButton")
bt_barbara.grid(row=1, column=2)
bt_beidou = ttk.Button(root, image=beidou, style="my.TButton")
bt_beidou.grid(row=1, column=3)
bt_bennett = ttk.Button(root, image=bennett, style="my.TButton")
bt_bennett.grid(row=1, column=4)
bt_chongyun = ttk.Button(root, image=chongyun, style="my.TButton")
bt_chongyun.grid(row=1, column=5)
bt_diluc = ttk.Button(root, image=diluc, style="my.TButton")
bt_diluc.grid(row=1, column=6)
bt_diona = ttk.Button(root, image=diona, style="my.TButton")
bt_diona.grid(row=1, column=7)
bt_fischl = ttk.Button(root, image=fischl, style="my.TButton")
bt_fischl.grid(row=1, column=8)
bt_jean = ttk.Button(root, image=jean, style="my.TButton")
bt_jean.grid(row=1, column=9)
bt_albedo = ttk.Button(root, image=albedo, style="my.TButton")
bt_albedo.grid(row=1, column=0)
bt_amber = ttk.Button(root, image=amber, style="my.TButton")
bt_amber.grid(row=1, column=1)
bt_barbara = ttk.Button(root, image=barbara, style="my.TButton")
bt_barbara.grid(row=1, column=2)
bt_beidou = ttk.Button(root, image=beidou, style="my.TButton")
bt_beidou.grid(row=1, column=3)
bt_bennett = ttk.Button(root, image=bennett, style="my.TButton")
bt_bennett.grid(row=1, column=4)
bt_chongyun = ttk.Button(root, image=chongyun, style="my.TButton")
bt_chongyun.grid(row=1, column=5)
bt_diluc = ttk.Button(root, image=diluc, style="my.TButton")
bt_diluc.grid(row=1, column=6)
bt_diona = ttk.Button(root, image=diona, style="my.TButton")
bt_diona.grid(row=1, column=7)
bt_fischl = ttk.Button(root, image=fischl, style="my.TButton")
bt_fischl.grid(row=1, column=8)
bt_jean = ttk.Button(root, image=jean, style="my.TButton")
bt_jean.grid(row=1, column=9)
bt_albedo = ttk.Button(root, image=albedo, style="my.TButton")
bt_albedo.grid(row=1, column=0)
bt_amber = ttk.Button(root, image=amber, style="my.TButton")
bt_amber.grid(row=1, column=1)
bt_barbara = ttk.Button(root, image=barbara, style="my.TButton")
bt_barbara.grid(row=1, column=2)
bt_beidou = ttk.Button(root, image=beidou, style="my.TButton")
bt_beidou.grid(row=1, column=3)
bt_bennett = ttk.Button(root, image=bennett, style="my.TButton")
bt_bennett.grid(row=1, column=4)
bt_chongyun = ttk.Button(root, image=chongyun, style="my.TButton")
bt_chongyun.grid(row=1, column=5)
bt_diluc = ttk.Button(root, image=diluc, style="my.TButton")
bt_diluc.grid(row=1, column=6)
bt_diona = ttk.Button(root, image=diona, style="my.TButton")
bt_diona.grid(row=1, column=7)
bt_fischl = ttk.Button(root, image=fischl, style="my.TButton")
bt_fischl.grid(row=1, column=8)
bt_jean = ttk.Button(root, image=jean, style="my.TButton")
bt_jean.grid(row=1, column=9)
bt_albedo = ttk.Button(root, image=albedo, style="my.TButton")
bt_albedo.grid(row=1, column=0)
bt_amber = ttk.Button(root, image=amber, style="my.TButton")
bt_amber.grid(row=1, column=1)
bt_barbara = ttk.Button(root, image=barbara, style="my.TButton")
bt_barbara.grid(row=1, column=2)
bt_beidou = ttk.Button(root, image=beidou, style="my.TButton")
bt_beidou.grid(row=1, column=3)
bt_bennett = ttk.Button(root, image=bennett, style="my.TButton")
bt_bennett.grid(row=1, column=4)
bt_chongyun = ttk.Button(root, image=chongyun, style="my.TButton")
bt_chongyun.grid(row=1, column=5)
bt_diluc = ttk.Button(root, image=diluc, style="my.TButton")
bt_diluc.grid(row=1, column=6)
bt_diona = ttk.Button(root, image=diona, style="my.TButton")
bt_diona.grid(row=1, column=7)
bt_fischl = ttk.Button(root, image=fischl, style="my.TButton")
bt_fischl.grid(row=1, column=8)
bt_jean = ttk.Button(root, image=jean, style="my.TButton")
bt_jean.grid(row=1, column=9)
bt_albedo = ttk.Button(root, image=albedo, style="my.TButton")
bt_albedo.grid(row=1, column=0)
bt_amber = ttk.Button(root, image=amber, style="my.TButton")
bt_amber.grid(row=1, column=1)
bt_barbara = ttk.Button(root, image=barbara, style="my.TButton")
bt_barbara.grid(row=1, column=2)
bt_beidou = ttk.Button(root, image=beidou, style="my.TButton")
bt_beidou.grid(row=1, column=3)
bt_bennett = ttk.Button(root, image=bennett, style="my.TButton")
bt_bennett.grid(row=1, column=4)
bt_chongyun = ttk.Button(root, image=chongyun, style="my.TButton")
bt_chongyun.grid(row=1, column=5)
bt_diluc = ttk.Button(root, image=diluc, style="my.TButton")
bt_diluc.grid(row=1, column=6)
bt_diona = ttk.Button(root, image=diona, style="my.TButton")
bt_diona.grid(row=1, column=7)
bt_fischl = ttk.Button(root, image=fischl, style="my.TButton")
bt_fischl.grid(row=1, column=8)
bt_jean = ttk.Button(root, image=jean, style="my.TButton")
bt_jean.grid(row=1, column=9)
bt_albedo = ttk.Button(root, image=albedo, style="my.TButton")
bt_albedo.grid(row=1, column=0)
bt_amber = ttk.Button(root, image=amber, style="my.TButton")
bt_amber.grid(row=1, column=1)
bt_barbara = ttk.Button(root, image=barbara, style="my.TButton")
bt_barbara.grid(row=1, column=2)
bt_beidou = ttk.Button(root, image=beidou, style="my.TButton")
bt_beidou.grid(row=1, column=3)
bt_bennett = ttk.Button(root, image=bennett, style="my.TButton")
bt_bennett.grid(row=1, column=4)
bt_chongyun = ttk.Button(root, image=chongyun, style="my.TButton")
bt_chongyun.grid(row=1, column=5)
bt_diluc = ttk.Button(root, image=diluc, style="my.TButton")
bt_diluc.grid(row=1, column=6)
bt_diona = ttk.Button(root, image=diona, style="my.TButton")
bt_diona.grid(row=1, column=7)
bt_fischl = ttk.Button(root, image=fischl, style="my.TButton")
bt_fischl.grid(row=1, column=8)
bt_jean = ttk.Button(root, image=jean, style="my.TButton")
bt_jean.grid(row=1, column=9)
bt_albedo = ttk.Button(root, image=albedo, style="my.TButton")
bt_albedo.grid(row=1, column=0)
bt_amber = ttk.Button(root, image=amber, style="my.TButton")
bt_amber.grid(row=1, column=1)
bt_barbara = ttk.Button(root, image=barbara, style="my.TButton")
bt_barbara.grid(row=1, column=2)
bt_beidou = ttk.Button(root, image=beidou, style="my.TButton")
bt_beidou.grid(row=1, column=3)
bt_bennett = ttk.Button(root, image=bennett, style="my.TButton")
bt_bennett.grid(row=1, column=4)
bt_chongyun = ttk.Button(root, image=chongyun, style="my.TButton")
bt_chongyun.grid(row=1, column=5)
bt_diluc = ttk.Button(root, image=diluc, style="my.TButton")
bt_diluc.grid(row=1, column=6)
bt_diona = ttk.Button(root, image=diona, style="my.TButton")
bt_diona.grid(row=1, column=7)
bt_fischl = ttk.Button(root, image=fischl, style="my.TButton")
bt_fischl.grid(row=1, column=8)
bt_jean = ttk.Button(root, image=jean, style="my.TButton")
bt_jean.grid(row=1, column=9)

bt_kaeya = ttk.Button(root, image=kaeya, style="my.TButton")
bt_kaeya.grid(row=2, column=0)
bt_qeqing = ttk.Button(root, image=qeqing, style="my.TButton")
bt_qeqing.grid(row=2, column=1)
bt_klee = ttk.Button(root, image=klee, style="my.TButton")
bt_klee.grid(row=2, column=2)
bt_lisa = ttk.Button(root, image=lisa, style="my.TButton")
bt_lisa.grid(row=2, column=3)
bt_mona = ttk.Button(root, image=mona, style="my.TButton")
bt_mona.grid(row=2, column=4)
bt_ningguang = ttk.Button(root, image=ningguang, style="my.TButton")
bt_ningguang.grid(row=2, column=5)
bt_noelle = ttk.Button(root, image=noelle, style="my.TButton")
bt_noelle.grid(row=2, column=6)
bt_qiqi = ttk.Button(root, image=qiqi, style="my.TButton")
bt_qiqi.grid(row=2, column=7)
bt_razor = ttk.Button(root, image=razor, style="my.TButton")
bt_razor.grid(row=2, column=8)
bt_sucrose = ttk.Button(root, image=sucrose, style="my.TButton")
bt_sucrose.grid(row=2, column=9)

bt_tartaglia = ttk.Button(root, image=tartaglia, style="my.TButton")
bt_tartaglia.grid(row=3, column=0)
bt_traveler_Anemo = ttk.Button(root, image=traveler_Anemo, style="my.TButton")
bt_traveler_Anemo.grid(row=3, column=1)
bt_traveler_Geo = ttk.Button(root, image=traveler_Geo, style="my.TButton")
bt_traveler_Geo.grid(row=3, column=2)
bt_venti = ttk.Button(root, image=venti, style="my.TButton")
bt_venti.grid(row=3, column=3)
bt_xiangling = ttk.Button(root, image=xiangling, style="my.TButton")
bt_xiangling.grid(row=3, column=4)
bt_xiao = ttk.Button(root, image=xiao, style="my.TButton")
bt_xiao.grid(row=3, column=5)
bt_xingqiu = ttk.Button(root, image=xingqiu, style="my.TButton")
bt_xingqiu.grid(row=3, column=6)
bt_xinyan = ttk.Button(root, image=xinyan, style="my.TButton")
bt_xinyan.grid(row=3, column=7)
bt_zhongli = ttk.Button(root, image=zhongli, style="my.TButton")
bt_zhongli.grid(row=3, column=8)


root.mainloop()
