from tkinter import PhotoImage

albedo = PhotoImage(file="img/Characters/Albedo.png")
amber = PhotoImage(file="img/Characters/Amber.png")
barbara = PhotoImage(file="img/Characters/Barbara.png")
beidou = PhotoImage(file="img/Characters/Beidou.png")
bennett = PhotoImage(file="img/Characters/Bennett.png")
chongyun = PhotoImage(file="img/Characters/Chongyun.png")
diluc = PhotoImage(file="img/Characters/Diluc.png")
diona = PhotoImage(file="img/Characters/Diona.png")
fischl = PhotoImage(file="img/Characters/Fischl.png")
jean = PhotoImage(file="img/Characters/Jean.png")
kaeya = PhotoImage(file="img/Characters/Kaeya.png")
keqing = PhotoImage(file="img/Characters/Keqing.png")
klee = PhotoImage(file="img/Characters/Klee.png")
lisa = PhotoImage(file="img/Characters/Lisa.png")
mona = PhotoImage(file="img/Characters/Mona.png")
ningguang = PhotoImage(file="img/Characters/Ningguang.png")
noelle = PhotoImage(file="img/Characters/Noelle.png")
qiqi = PhotoImage(file="img/Characters/Qiqi.png")
razor = PhotoImage(file="img/Characters/Razor.png")
sucrose = PhotoImage(file="img/Characters/Sucrose.png")
tartaglia = PhotoImage(file="img/Characters/Tartaglia.png")
traveler_Anemo = PhotoImage(file="img/Characters/Traveler (Anemo).png")
traveler_Geo = PhotoImage(file="img/Characters/Traveler (Geo).png")
venti = PhotoImage(file="img/Characters/Venti.png")
xiangling = PhotoImage(file="img/Characters/Xiangling.png")
xiao = PhotoImage(file="img/Characters/Xiao.png")
xingqiu = PhotoImage(file="img/Characters/Xingqiu.png")
xinyan = PhotoImage(file="img/Characters/Xinyan.png")
zhongli = PhotoImage(file="img/Characters/Zhongli.png")

